### PR TITLE
Adding README.adoc file

### PR DESCRIPTION
**Pull request by kasturinarra**
Adding a README.adoc file as per https://github.com/rh-impact/pnt-hackathon-2022/issues/41 @porridge could you please help merge ? thanks !!

### CODE REVIEW

**Comment by porridge** [comment]
I have a couple of questions @kasturinarra 
- there already is a README.md in this directory, so having two READMEs side by side could be confusing
- I'm not sure how useful it is to document all the options for the `optipng` binary right now, if the only way to use them is via interactive container execution (which I understand is not something feasible for a typical ChRIS user).

**Comment by kasturinarra** [comment]
> 



> I have a couple of questions @kasturinarra
> 
> * there already is a README.md in this directory, so having two READMEs side by side could be confusing
I am not sure why such a task was added then in the first place if we were not supposed to have two README files , also  when i checked others repo's i do see we are having README.adoc as well, so added one. For example see here https://github.com/rh-impact/pl-deoldify/pull/3/files
> * I'm not sure how useful it is to document all the options for the `optipng` binary right now, if the only way to use them is via interactive container execution (which I understand is not something feasible for a typical ChRIS user).
I did mention both the ways, interactive and non-interactive.

**Comment by kasturinarra** [comment]
@porridge that being said if you think this does not make sense, i am okay to close this, thanks !!

**Comment by kasturinarra** [comment]
@porridge i spoke to @computate and based on his suggestions i have removed the README.adoc file and added some content into the README.rst which is present here. Would you mind taking a look and see if you could merge ? thanks !!

**Review by computate — APPROVED** [review]

**Pull request merged**
